wiki_title = "//h1[@id='Добро_пожаловать_в_Википедию,']"
pdf_download = "//a[@title='Скачать эту страницу как файл PDF']"
favorite_img = "//div[@id='main-tfa']/child::div[@class='main-box-content']/descendant::img[@class='mw-file-element']"
enter_comon_text = "//tt[text()='Редактировать просто — что введёшь, то и увидишь.']"
lang_settings = "//button[@class='uls-settings-trigger']"
login_label = "//label[@for='wpName1']"
login_field = "//input[@id='wpName1']"
pass_label = "//label[@for='wpPassword1']"
pass_field = "//input[@id='wpPassword1']"
check_box = "//input[@id='wpRemember']"
enter_button = "//button[@id='wpLoginAttempt']"
login_help = "//a[text()='Помощь по входу']"
pass_reset = "//a[@title='Служебная:Сброс пароля']"
join = "//a[@id='mw-createaccount-join']"
